//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class genie
    {
        public int genieid { get; set; }
        public Nullable<int> persontypeid { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<int> geniestatusid { get; set; }
    }
}
