//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class helpcentraldbEntities : DbContext
    {
        public helpcentraldbEntities()
            : base("name=helpcentraldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<orderhistory> orderhistorys { get; set; }
        public virtual DbSet<workrequest> workrequests { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<genie> genies { get; set; }
        public virtual DbSet<orderstatus> orderstatuses { get; set; }
        public virtual DbSet<persontype> persontypes { get; set; }
        public virtual DbSet<requesttype> requesttypes { get; set; }
        public virtual DbSet<schedule> schedules { get; set; }
        public virtual DbSet<scheduletype> scheduletypes { get; set; }
        public virtual DbSet<servicetype> servicetypes { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<scheduler> schedulers { get; set; }
    }
}
