//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderid { get; set; }
        public Nullable<int> servicetypeid { get; set; }
        public Nullable<int> orderstatusid { get; set; }
        public Nullable<int> customerid { get; set; }
        public Nullable<int> estimatedhours { get; set; }
        public Nullable<int> actualhours { get; set; }
        public Nullable<int> perferredgenieid { get; set; }
        public string specialrequest { get; set; }
        public Nullable<System.DateTime> dateplaced { get; set; }
        public Nullable<System.DateTime> datecompleted { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
