//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int scheduleid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<int> scheduletypeid { get; set; }
        public string daysoftheweeklist { get; set; }
        public Nullable<int> numberofrepeatingweeks { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<int> duration { get; set; }
    }
}
