//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class workrequest
    {
        public int workrequestid { get; set; }
        public Nullable<int> genieid { get; set; }
        public Nullable<int> requesttypeid { get; set; }
        public Nullable<int> servicetypelistid { get; set; }
        public Nullable<int> scheduleid { get; set; }
    }
}
