//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HbSoft.HCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderstatus
    {
        public int orderstatusid { get; set; }
        public string name { get; set; }
    }
}
