//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HbSoft.HCApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicetype
    {
        public int servicetypeid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> interviewrequired { get; set; }
        public Nullable<float> hourlyfee { get; set; }
        public string qualificationsrequired { get; set; }
    }
}
